name: CI to ECR
on: 
  push:
    branches: [master,testnet,feature/ci]

jobs:
  docker-build-push:
    # Name the Job
    name: Build and push
    runs-on: build
    outputs:
      registry: ${{ steps.build.outputs.registry }}
      image_tag: ${{ steps.build.outputs.image_tag }}
    steps:
      - name: test
        env:
          NAMESPACE: testnet
        run: |
          if [ ${GITHUB_REF##*/} = 'master' ]; then NAMESPACE=default; fi
          if [ ${GITHUB_REF##*/} = 'ci' ]; then NAMESPACE=default 1; fi
          echo $NAMESPACE
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        id: checkout 
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push image to AWS ECR
        id: build
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: velas-wallet
          IMAGE_TAG: ${{github.sha}}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=registry::$ECR_REGISTRY/$ECR_REPOSITORY"
          echo "::set-output name=image_tag::$IMAGE_TAG"
  deploy:
    name: deploy via Helmfile
    runs-on: deploy
    needs: docker-build-push
    steps:
      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@v0.6.0
        with:
          helmfile-version: "v0.131.0"
      - name: Check out my other private repo
        uses: actions/checkout@master
        with:
          repository: velas/velas-infra
          ssh-key: ${{ secrets.INFRA_SSH_KEY }}
      - name: add aws-iam-authenticator
        uses: prepor/action-aws-iam-authenticator@master
      - name: Deploy via helmfile
        env:
          ECR_REGISTRY: ${{ needs.docker-build-push.outputs.registry }}
          IMAGE_TAG: ${{ needs.docker-build-push.outputs.image_tag }}
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          NAMESPACE: testnet
        run: |
          if [ `helm plugin list|grep diff|wc -l` -eq '0' ]; then helm plugin install https://github.com/databus23/helm-diff ; fi
          if [ ${GITHUB_REF##*/} -eq 'master' ]; then NAMESPACE=default; fi
          mkdir -p ~/.kube && echo $KUBE_CONFIG_DATA|base64 --decode > ~/.kube/config
          cd deploy
          helmfile -e nodes -l namespace=testnet,name=velas-wallet apply  --set image.tag=$IMAGE_TAG,image.repository=$ECR_REGISTRY/$ECR_REPOSITORY

